const placesContainer= document.getElementById('new')
console.log(placesContainer)
console.log(placesContainer.parentNode)
console.log(placesContainer.parentNode.parentNode)
console.log(placesContainer.parentNode.parentNode.parentNode)
console.log(placesContainer.parentNode.parentNode.parentNode.parentNode)